spring.datasource.url=jdbc:postgresql://ep-spring-breeze-ant74iwh-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4ML6NFlhTpBy
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false